build:
  script: "sh gradlew shadowJar ; cp build/libs/kds-all.jar kds.jar"
  artifacts:
    paths:
      - "kds.jar"
    expire_in: 3 days
deploy:
  stage: deploy
  script: "cp kds.jar /home/kds/run/update/kds.jar; sudo /home/kds/notify.sh"